create table glioma__cohort_dx_neurofibromatosis as 
select distinct * from 
 glioma__cohort_study_population_dx , 
glioma__valueset_dx_neurofibromatosis
WHERE
glioma__cohort_study_population_dx.dx_code = glioma__valueset_dx_neurofibromatosis.code and 
glioma__cohort_study_population_dx.dx_system = glioma__valueset_dx_neurofibromatosis.system