create table glioma__cohort_rx_cancer_directed as 
select * from 
 glioma__cohort_study_population_rx , 
glioma__valueset_rx_cancer_directed
WHERE
glioma__cohort_study_population_rx.rx_code = glioma__valueset_rx_cancer_directed.code and 
glioma__cohort_study_population_rx.rx_system = glioma__valueset_rx_cancer_directed.system