create table glioma__cohort_rx_everolimus as 
select distinct * from 
 glioma__cohort_study_population_rx , 
glioma__valueset_rx_everolimus
WHERE
glioma__cohort_study_population_rx.rx_code = glioma__valueset_rx_everolimus.code and 
glioma__cohort_study_population_rx.rx_system = glioma__valueset_rx_everolimus.system