create table glioma__cohort_rx_chemo_bevacizumab as 
select distinct * from 
 glioma__cohort_study_population_rx , 
glioma__valueset_rx_chemo_bevacizumab
WHERE
glioma__cohort_study_population_rx.rx_code = glioma__valueset_rx_chemo_bevacizumab.code and 
glioma__cohort_study_population_rx.rx_system = glioma__valueset_rx_chemo_bevacizumab.system