import os
CUMULUS_CACHE_PREFIX = os.environ.get("CUMULUS_CACHE_PREFIX", None)
CUMULUS_CUBE_AS_VIEW = int(os.environ.get("CUMULUS_CUBE_AS_VIEW") or 0)
CUMULUS_CUBE_MIN_SUBJECTS = int(os.environ.get("CUMULUS_CUBE_MIN_SUBJECTS") or 10)

print('###########################################################')
print('[Settings]')
print()
print('Optional: Use cached copies of study population tables')
print('CUMULUS_CACHE_PREFIX', '=', CUMULUS_CACHE_PREFIX)
print()
print('Optional: Use VIEW instead of TABLE')
print('CUMULUS_CUBE_AS_VIEW', '=', CUMULUS_CUBE_AS_VIEW)
print()
print('Optional: Minimum number of patients per set size in CUBE data')
print('CUMULUS_CUBE_MIN_SUBJECTS', '=', CUMULUS_CUBE_MIN_SUBJECTS)
print()
print('###########################################################')
