study_prefix = "glioma"

[file_config.file_names]
"cohort matching glioma case definition (casedef)" = [
    "athena/glioma__cohort_casedef.sql",
]

"cohort glioma timeline (pre, index, index_post, post)" = [
    "athena/glioma__cohort_casedef_pre.sql",
    "athena/glioma__cohort_casedef_index.sql",
    "athena/glioma__cohort_casedef_index_post.sql",
    "athena/glioma__cohort_casedef_post.sql",
]

"sample glioma timeline (pre, index, index_post, post)" = [
    "athena/glioma__sample_casedef_pre.sql",
    "athena/glioma__sample_casedef_index.sql",
    "athena/glioma__sample_casedef_index_post.sql",
    "athena/glioma__sample_casedef_post.sql",
]

"cohort glioma co-occurence (dx, rx)" = [
    "athena/glioma__cohort_dx.sql",
    "athena/glioma__cohort_rx.sql",
]

#[export_config]