study_prefix = "glioma"

# See Also llm/cube.toml

[file_config.file_names]
"cube counts (casdef, dx, rx, casedef)" = [
    "athena/glioma__cube_patient_casedef.sql",
    "athena/glioma__cube_patient_dx.sql",
    "athena/glioma__cube_patient_rx.sql",
    "athena/glioma__cube_encounter_casedef.sql",
    "athena/glioma__cube_document_sample_casedef_index_post.sql",
]
