config_type="file_upload"

[tables.valueset_diag_brain_mri]
file = "valueset_data/diag_brain_mri.json.valueset.tsv"

[tables.valueset_diag_head_neck]
file = "valueset_data/diag_head_neck.json.valueset.tsv"

[tables.valueset_diag_radiology]
file = "valueset_data/diag_radiology.json.valueset.tsv"

[tables.valueset_dx_brain_tumor]
file = "valueset_data/dx_brain_tumor.json.valueset.tsv"

[tables.valueset_dx_cancer]
file = "valueset_data/dx_cancer.json.valueset.tsv"

[tables.valueset_dx_diabetes]
file = "valueset_data/dx_diabetes.json.valueset.tsv"

[tables.valueset_dx_focal_deficit]
file = "valueset_data/dx_focal_deficit.json.valueset.tsv"

[tables.valueset_dx_neuro]
file = "valueset_data/dx_neuro.json.valueset.tsv"

[tables.valueset_dx_neuropathy]
file = "valueset_data/dx_neuropathy.json.valueset.tsv"

[tables.valueset_lab_gene_alk]
file = "valueset_data/lab_gene_alk.json.valueset.tsv"

[tables.valueset_lab_gene_braf]
file = "valueset_data/lab_gene_braf.json.valueset.tsv"

[tables.valueset_lab_gene_ntrk]
file = "valueset_data/lab_gene_ntrk.json.valueset.tsv"

[tables.valueset_lab_gene_ret]
file = "valueset_data/lab_gene_ret.json.valueset.tsv"

[tables.valueset_lab_gene_ros1]
file = "valueset_data/lab_gene_ros1.json.valueset.tsv"

[tables.valueset_lab_gene_test]
file = "valueset_data/lab_gene_test.json.valueset.tsv"

[tables.valueset_proc_neurosurgery]
file = "valueset_data/proc_neurosurgery.json.valueset.tsv"

[tables.valueset_rx_cancer_directed]
file = "valueset_data/rx_cancer_directed.json.valueset.tsv"

[tables.valueset_rx_chemo]
file = "valueset_data/rx_chemo.json.valueset.tsv"

[tables.valueset_rx_chemo_advanced]
file = "valueset_data/rx_chemo_advanced.json.valueset.tsv"

[tables.valueset_rx_chemo_bevacizumab]
file = "valueset_data/rx_chemo_bevacizumab.json.valueset.tsv"

[tables.valueset_rx_chemo_platinum]
file = "valueset_data/rx_chemo_platinum.json.valueset.tsv"

[tables.valueset_rx_chemo_platinum_carboplatin]
file = "valueset_data/rx_chemo_platinum_carboplatin.json.valueset.tsv"

[tables.valueset_rx_chemo_vincristine]
file = "valueset_data/rx_chemo_vincristine.json.valueset.tsv"

[tables.valueset_rx_endo_diabetes]
file = "valueset_data/rx_endo_diabetes.json.valueset.tsv"

[tables.valueset_rx_endo_therapy]
file = "valueset_data/rx_endo_therapy.json.valueset.tsv"
