# study prefix is the name of the tablepace cumulus_library.StudyManifest().get_study_prefix() 
study_prefix = "glioma"

[file_config.file_names]

# -----------------------------------------------------------------------------
## Valuesets to download
#    "vsac.toml" = [
#        "vsac.toml"
#    ]

"file_upload.toml" = [
    "file_upload.toml"
]

"file_upload_vsac.toml" = [
    "file_upload_vsac.toml"
]

# -----------------------------------------------------------------------------
# Study population
"inclusion criteria for study population" = [
    "athena/glioma__include_gender.sql",
    "athena/glioma__include_age_at_visit.sql",
    "athena/glioma__include_utilization.sql",
    "athena/glioma__include_study_period.sql",
]

"study period" = [
    "athena/glioma__cohort_study_period.sql",
]

"study population" = [
    "athena/glioma__cohort_study_population.sql",
]

"study population (dx, rx, lab, proc, doc, diag)" = [
    "athena/glioma__cohort_study_population_dx.sql",
    "athena/glioma__cohort_study_population_rx.sql",
    "athena/glioma__cohort_study_population_lab.sql",
    "athena/glioma__cohort_study_population_doc.sql",
    "athena/glioma__cohort_study_population_diag.sql",
    "athena/glioma__cohort_study_population_proc.sql",
]

# -----------------------------------------------------------------------------
#  *CASE DEFINITION* pLGG (Pediatric Low Grade Glioma)

"cohort case definition"= [
	"athena/glioma__cohort_casedef.sql",
]

"samples of case definition [pre, peri, peri_post, post]"= [
	"athena/glioma__sample_casedef_pre.sql",
	"athena/glioma__sample_casedef_peri.sql",
	"athena/glioma__sample_casedef_peri_post.sql",
	"athena/glioma__sample_casedef_post.sql",
]

"samples for LLM tasks" = [
    "athena/glioma__sample_casedef_task.sql"
]

"samples for LLM tasks diagnosis, drug, gene, surgery, progression" = [
    "athena/glioma__sample_casedef_task_diagnosis.sql",
    "athena/glioma__sample_casedef_task_drug.sql",
    "athena/glioma__sample_casedef_task_gene.sql",
    "athena/glioma__sample_casedef_task_surgery.sql",
    "athena/glioma__sample_casedef_task_progression.sql",
]

"cohort glioma co-occurence (dx, rx)" = [
    "athena/glioma__cohort_dx.sql",
    "athena/glioma__cohort_rx.sql",
]

# # -----------------------------------------------------------------------------
# Variable cohorts
"variable cohorts"= [
	"athena/glioma__cohort_diag_brain_mri.sql",
	"athena/glioma__cohort_diag_head_neck.sql",
	"athena/glioma__cohort_diag_pathology.sql",
	"athena/glioma__cohort_diag_radiology.sql",
	"athena/glioma__cohort_dx_brain_tumor.sql",
	"athena/glioma__cohort_dx_cancer.sql",
	"athena/glioma__cohort_dx_endo_diabetes.sql",
	"athena/glioma__cohort_dx_focal_deficit.sql",
	"athena/glioma__cohort_dx_neuro.sql",
	"athena/glioma__cohort_dx_neurofibromatosis.sql",
	"athena/glioma__cohort_dx_neuropathy.sql",
	"athena/glioma__cohort_lab_mtor_sirolimus.sql",
	"athena/glioma__cohort_proc_neurosurgery.sql",
	"athena/glioma__cohort_rx_cancer_directed.sql",
	"athena/glioma__cohort_rx_chemo.sql",
	"athena/glioma__cohort_rx_chemo_advanced.sql",
	"athena/glioma__cohort_rx_chemo_bevacizumab.sql",
	"athena/glioma__cohort_rx_chemo_platinum.sql",
	"athena/glioma__cohort_rx_chemo_platinum_carboplatin.sql",
	"athena/glioma__cohort_rx_chemo_vincristine.sql",
	"athena/glioma__cohort_rx_endo_diabetes.sql",
	"athena/glioma__cohort_rx_endo_therapy.sql",
	"athena/glioma__cohort_rx_mtor_everolimus.sql",
	"athena/glioma__cohort_rx_mtor_sirolimus.sql",
]

"variable union (structured)" = [
    "athena/glioma__cohort_variable_union.sql"
]

"variable wide (structured)" = [
    "athena/glioma__cohort_variable_wide.sql"
]

# # -----------------------------------------------------------------------------
# LLM
#
#    "glioma LLM (ICDO: grade, topography, morphology, behavior)" = [
#        "athena/glioma__llm_dx.sql",
#    ]
#
#    "glioma LLM (surgery, drug, gene, variant)" = [
#        "athena/glioma__llm_surgery.sql",
#        "athena/glioma__llm_drug.sql",
#        "athena/glioma__llm_gene.sql",
#        "athena/glioma__llm_variant.sql",
#    ]
#
#    "glioma LLM cube counts" = [
#        "athena/glioma__cube_patient_llm_dx.sql",
#        "athena/glioma__cube_patient_llm_drug.sql",
#        "athena/glioma__cube_patient_llm_surgery.sql",
#        "athena/glioma__cube_patient_llm_gene.sql",
#        "athena/glioma__cube_patient_llm_variant.sql",
#    ]

#    "cube.toml" = [
#        "cube.toml"
#    ]


#    "llm.toml" = [
#        "llm.toml"
#    ]

[export_config]
#    count_list = [
#        "glioma__cube_patient_llm_drug",
#        "glioma__cube_patient_llm_dx"
#    ]
#
#    meta_list = [
#        "glioma__meta_date",
#    ]