# study prefix is the name of the tablepace cumulus_library.StudyManifest().get_study_prefix() 
study_prefix = "glioma"

[file_config.file_names]
# -----------------------------------------------------------------------------
## Upload CSV/TSV curated files
"file_upload.toml" = [
    "file_upload.toml"
]

## -----------------------------------------------------------------------------
# Variable cohorts
"variable cohorts"= [
    "athena/glioma__cohort_diag_brain_mri.sql",
    "athena/glioma__cohort_diag_head_neck.sql",
    "athena/glioma__cohort_diag_pathology.sql",
    "athena/glioma__cohort_diag_radiology.sql",
    "athena/glioma__cohort_dx_brain_tumor.sql",
    "athena/glioma__cohort_dx_cancer.sql",
    "athena/glioma__cohort_dx_endo_diabetes.sql",
    "athena/glioma__cohort_dx_focal_deficit.sql",
    "athena/glioma__cohort_dx_neuro.sql",
    "athena/glioma__cohort_dx_neurofibromatosis.sql",
    "athena/glioma__cohort_dx_neuropathy.sql",
    "athena/glioma__cohort_lab_mtor_sirolimus.sql",
    "athena/glioma__cohort_proc_neurosurgery.sql",
    "athena/glioma__cohort_rx_cancer_directed.sql",
    "athena/glioma__cohort_rx_chemo.sql",
    "athena/glioma__cohort_rx_chemo_advanced.sql",
    "athena/glioma__cohort_rx_chemo_bevacizumab.sql",
    "athena/glioma__cohort_rx_chemo_platinum.sql",
    "athena/glioma__cohort_rx_chemo_platinum_carboplatin.sql",
    "athena/glioma__cohort_rx_chemo_vincristine.sql",
    "athena/glioma__cohort_rx_endo_diabetes.sql",
    "athena/glioma__cohort_rx_endo_therapy.sql",
    "athena/glioma__cohort_rx_mtor_everolimus.sql",
    "athena/glioma__cohort_rx_mtor_sirolimus.sql",
]

"variable union (structured)" = [
    "athena/glioma__cohort_variable_union.sql"
]

"variable wide (structured)" = [
    "athena/glioma__cohort_variable_wide.sql"
]

"cube FHIR"= [
    "athena/glioma__cube_patient_variable_union.sql",
    "athena/glioma__cube_encounter_variable_union.sql",
    "athena/glioma__cube_patient_variable_wide_diag.sql",
    "athena/glioma__cube_patient_variable_wide_neuro.sql",
    "athena/glioma__cube_patient_variable_wide_endo.sql",
    "athena/glioma__cube_patient_variable_wide_cancer.sql",
]
##
## -----------------------------------------------------------------------------
## LLM note types (dependancy: DocumentTypeAnnotation)

"samples for LLM tasks" = [
    "athena/glioma__sample_casedef_task.sql"
]

"samples for LLM tasks diagnosis, drug, gene, surgery, progression" = [
    "athena/glioma__sample_casedef_task_diagnosis.sql",
    "athena/glioma__sample_casedef_task_drug.sql",
    "athena/glioma__sample_casedef_task_gene.sql",
    "athena/glioma__sample_casedef_task_surgery.sql",
    "athena/glioma__sample_casedef_task_progression.sql",
]

# -----------------------------------------------------------------------------
# Export to Cumulus aggregator
[export_config]
count_list = [
    "glioma__cube_encounter_variable_union",
    "glioma__cube_patient_variable_union",
    "glioma__cube_patient_variable_wide_diag",
]

meta_list = [
    "glioma__meta_date",
    "glioma__meta_version",
]
