config_type="valueset"
table_prefix = "rx_class_idh"

[umls_stewards.idh]
sab = "RXNORM"# "MED-RT"
search_terms = [
#    "Isocitrate Dehydrogenase 1 Inhibitor",
#    "Isocitrate Dehydrogenase 2 Inhibitor",
#    "IDH1 inhibitor",
#    "IDH2 inhibitor",
    "Ivosidenib",
    "Vorasidenib",
    "Enasidenib"

]