config_type="valueset"
table_prefix = "rx_class_pan_raf"

[umls_stewards.rx_class_pan_raf]
sab = "RXNORM"
search_terms = [
    "tovorafenib",
    "DAY101",
    # "Belvarafenib",
    # "Lifirafenib",
    # "Naporafenib"
    # "LXH254"
]