config_type="valueset"
table_prefix = "rx_class_platinum"

[umls_stewards.rx_class_platinum]
sab = "ATC"
search_terms = ["Platinum-based Drug", "Platinum Compounds", "Platinum Antineoplastic Compound", "cisplatin"]

[vsac_stewards]
vsac_rx_class_platinum="2.16.840.1.113762.1.4.1260.71"
