config_type="valueset"
table_prefix = "rx_class_antimetabolite"

[umls_stewards.antimetabolite]
sab = "RXNORM"
search_terms = [
    'antimetabolites',
    'purine analog',
    'thioguanine',
    'methotrexate',
    'mercaptopurine',
    'mycophenolate mofetil',
    'mycophenolic acid',
    'azathioprine']