config_type="valueset"
table_prefix = "rx_class"

# [umls_stewards.platinum]
# TODO https://github.com/smart-on-fhir/cumulus-library/issues/442#issuecomment-3745004450
# sab = ["MED-RT", "RXNORM", "SNOMEDCT_US", "NCI"]
# search_terms = ["Platinum-based Drug", "Platinum Compounds", "Platinum Antineoplastic Compound", "cisplatin"]

[vsac_stewards]
rx_class_vsac_platinum="2.16.840.1.113762.1.4.1260.71"
