config_type="valueset"
table_prefix = "rx_in"

[umls_stewards.bevacizumab]
sab = "RXNORM"
search_terms = ["Bevacizumab","Avastin"]

[vsac_stewards]
rx_chemo_bevacizumab="2.16.840.1.113762.1.4.1116.179"
